#!/usr/bin/env bash
#
# render-config.sh — generate /etc/cloudflared/config.yml from apps/*.conf and
# cloudflared/host-ingress.conf.
#
# Each app's HOSTNAME and LOCAL_PORT become one ingress rule, plus whatever
# host-ingress.conf lists for the Pi itself.
#
# The generated file is overwritten on every self-update, so editing
# /etc/cloudflared/config.yml by hand does not add anything — it survives until
# the next pull and then vanishes.
#
#     /opt/rpi/cloudflared/render-config.sh            # render, install, reload
#     /opt/rpi/cloudflared/render-config.sh --dry-run  # print, change nothing
#
# Run by rpi-selfupdate after it pulls, so the deployed config always matches
# the repo. Idempotent: if nothing changed, cloudflared is not touched.

set -euo pipefail

HERE="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
# shellcheck disable=SC1091
. "${HERE}/lib/appconf.sh"

DEST=/etc/cloudflared/config.yml
DRY=0
[ "${1:-}" = "--dry-run" ] && DRY=1

# The tunnel UUID is discovered from the credentials file rather than hardcoded,
# so a rebuilt Pi with a new tunnel needs no edit here.
CRED=$(ls -1 /etc/cloudflared/*.json 2>/dev/null | head -1)
[ -n "$CRED" ] || { echo "no tunnel credentials in /etc/cloudflared" >&2; exit 1; }
UUID=$(basename "$CRED" .json)

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<EOF
# GENERATED by cloudflared/render-config.sh — do not edit; regenerated on every
# self-update from apps/*.conf and cloudflared/host-ingress.conf.
#
# Add an app by writing apps/<name>.conf, then run:
#     sudo /opt/rpi/cloudflared/render-config.sh
#     sudo cloudflared tunnel route dns mypi <hostname>
#
# The tunnel dials OUT to Cloudflare: no router ports are forwarded and the
# dynamic residential IP is irrelevant. The UUID is an identifier, not a secret
# — the secret is the credentials file it names, which never leaves this host.

tunnel: ${UUID}
credentials-file: ${CRED}

# Survive brief wifi drops without tearing down the tunnel.
retries: 10
grace-period: 30s

# Metrics for the health collector; loopback only.
metrics: 127.0.0.1:60123

ingress:
EOF

for app in $(appconf_list); do
  ( appconf_load "$app"
    cat >> "$TMP" <<EOF
  - hostname: ${HOSTNAME}
    service: http://127.0.0.1:${LOCAL_PORT}
    originRequest:
      connectTimeout: 10s
      noHappyEyeballs: true
EOF
  )
done

# Services on the Pi itself — the dashboard and SSH. Listed rather than derived:
# there is no LOCAL_PORT to read, and SSH is not http.
HOST_INGRESS_CONF="${HERE}/cloudflared/host-ingress.conf"
if [ -f "$HOST_INGRESS_CONF" ]; then
  # shellcheck disable=SC1090
  . "$HOST_INGRESS_CONF"
  for entry in "${HOST_INGRESS[@]:-}"; do
    [ -n "$entry" ] || continue
    HOST="${entry%%|*}"
    SVC="${entry#*|}"
    printf '  - hostname: %s\n    service: %s\n' "$HOST" "$SVC" >> "$TMP"
    # originRequest tuning is HTTP-specific; applying it to an ssh:// origin is
    # meaningless at best.
    case "$SVC" in
      http://*|https://*)
        printf '    originRequest:\n      connectTimeout: 10s\n      noHappyEyeballs: true\n' >> "$TMP"
        ;;
    esac
  done
fi

cat >> "$TMP" <<'EOF'

  # Required catch-all. Anything not matched above gets a 404 rather than
  # being silently proxied somewhere unintended.
  - service: http_status:404
EOF

if [ "$DRY" = "1" ]; then cat "$TMP"; exit 0; fi

if cmp -s "$TMP" "$DEST"; then
  echo "cloudflared config unchanged"
  exit 0
fi

install -m 0644 "$TMP" "$DEST"
# Validate before reloading: a bad config would otherwise take the tunnel down
# and with it every app.
if ! cloudflared tunnel ingress validate >/dev/null 2>&1; then
  echo "generated config failed validation — NOT reloading" >&2
  cloudflared tunnel ingress validate || true
  exit 1
fi
systemctl reload-or-restart cloudflared
echo "cloudflared config updated and reloaded ($(appconf_list | wc -l | tr -d ' ') apps)"
